### ISSUE TITLE
[1.20.1] Found a few missing matter values

### ISSUE THREAD

**Issue by vizthex123** [Buuz135/Replication#12]
**Replication Version:**
1.0.2

**Titanium Version:**
3.8.27

Thermal Series Ender Dust has matter values, but AE2's doesn't:
![image](https://github.com/Buuz135/Replication/assets/31721920/fe61a575-0394-4f44-8690-74044e92d1b0)
![image](https://github.com/Buuz135/Replication/assets/31721920/9711d448-b7c4-469b-866c-b20abc434922)

Also noticed that they're not equal to the Ender Pearl's values:
![image](https://github.com/Buuz135/Replication/assets/31721920/22e75fc4-9176-46f0-98f0-79332e7d1d4b)

Pretty sure this is cuz of the Earth Charge recipe for all TE dusts.

Also, all dusts for various ores (but mainly the ones from TE) are missing matter values.

Other items with missing or incorrect values:
*I'll be doing M / R to suggest correct values (where M is the matter used to craft R, the result)*

- Bamboo and Stripped Bamboo Blocks: Doesn't match the value of Logs (and Stripped Bamboo has no matter), which makes their Stick recipes have incorrect sums (based on this recipe, each Stick should have 0.625 Earth and Organic instead of the 0.5 they have with Planks)

It seems like this happened because the Block of Bamboo has a custom value assigned even though you can craft it with 9 Bamboo.

- Sticks: Loses Organic, and should have 0.5 of each (2 Planks / the 4 Sticks it makes = 0.5)
- Wooden Slabs should be ~0.33 (2 Matter / 6 Slabs)
- All damage states of Anvils have the same Metallic value. I think it should degrade a bit each time since the damage would wear off some of the metal.
- Wither Skeleton Skulls don't have Nether matter

Item values that aren't equal when you've got extra mods installed:
- Copper Ingots don't evenly divide with Nuggets since they've only got 2 of each matter instead of the standard 9 that Iron and Gold have.
- Modded eggs with the `forge:eggs` tag don't have values. Should be a simple fix, and said fix should apply to every item with tags even if there's only 1 in vanilla (feathers, leather, etc.)

**Comment by Buuz135** [comment]
Fixed in 1.21
