### ISSUE TITLE
[1.20.1] Failed to Anaylze MAtter

### ISSUE THREAD

**Issue by Klouver-github** [Buuz135/Replication#15]
**DO NOT REPORT AN ISSUE IF YOU HAVEN'T TESTED THE ISSUE WITH THE LATEST VERSION IN CURSEFORGE**

**Replication Version:: latest

**Titanium Version:Latest

[Aequivaleo analysis runner: 1/FATAL] [co.ld.ae.an.AequivaleoReloadListener/]: Failed to analyze: [ad_astra:venus_orbit, create_dd:ponder, blue_skies:everdawn, minecraft:overworld, ad_astra:moon, twilightforest:twilight_forest, ad_astra:moon_orbit, ad_astra:mercury_orbit, blue_skies:everbright, ad_astra:mercury, ad_astra:mars_orbit, minecraft:the_nether, ad_astra:venus, transdimensionalmachines:cosmic_boundary, aether:the_aether, minecraft:the_end, mining_dimension:mining, createteleporters:pocket_dimension, ad_astra:mars, ad_astra:glacio_orbit, ad_astra:earth_orbit, lostcities:lostcity, ad_astra:glacio, deeper_dark:deeper_dark, leftbehind:pocket, rats:ratlantis]

**Comment by Buuz135** [comment]
Fixed in 1.21
