### ISSUE TITLE
[1.20.1] Matter values not being added to items no matter what I do

### ISSUE THREAD

**Issue by vizthex123** [Buuz135/Replication#21]
I've tried reloading the world and game, but it doesn't fix the issue. Even making a new world doesn't fix it, and running `/reload` does nothing.

Downgrading doesn't fix it, and reinstalling all 3 mods didn't work either.

**Replication Version:**
1.0.5

**Titanium Version:**
3.8.32

Also running v1.0.7 of Aequivaleo. Tested it with v0.1.132 and that didn't fix the issue.

**Crashlog If Applicable (Upload to pastebin/gist):**
https://gist.github.com/vizthex123/ffb662747358e8cf348613e566b87058

**Comment by vizthex123** [comment]
Update: Seems like it's delayed while trying to sync matter values, but it doesn't send the notification like it used to.

I'd also suggest adding a message in chat so it's more obvious when the sync is happening.

**Comment by Buuz135** [comment]
Fixed in 1.21
